name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install-requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env
        run: cp .env.example .env
      
      - name: Start Docker services
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 30
      
      - name: run-Tests
        run: |
          docker compose exec -T api python -m pytest
      
      - name: Stop Docker services
        if: always()
        run: docker compose down -v